"undefined"!=typeof DEMOBO&&(DEMOBO.maxPlayers=1,DEMOBO.stayOnBlur=!0,DEMOBO.appName="www.presentationdocs.com",DEMOBO.init=function(){demobo.setController({page:"presentation"});demobo.renderQR();demobo.addEventListener("input",function(a){0<demobo.getPlayerIndex(a.deviceID)||"demoboVolume"==a.source&&("down"==a.value?prevPage():"up"==a.value&&nextPage())},!1);demobo.addEventListener("swipe",function(a){0<demobo.getPlayerIndex(a.deviceID)||("left"==a.direction?prevPage():"right"==a.direction&&nextPage())},
!1);demobo.addEventListener("gesture",function(a){$("input[type='checkbox']").attr("checked")&&(0<demobo.getPlayerIndex(a.deviceID)||a.gestureName||nextPage())},!1);demobo.addEventListener("start",function(a){-1==demobo.getPlayerIndex(a.deviceID)&&addUser(a);toggleScreen()},!1);demobo.addEventListener("connected",addUser,!1);setTimeout(function(){demobo.getDeviceInfo("","addUser")},100)},demobo.renderBrowserWarning=function(){showMessage("We only support Safari and Chrome browsers on your laptop or desktop at this moment.",
"Sorry",!1);$(".ui-dialog-titlebar-close.ui-corner-all").hide()},1200>screen.width&&$("#wrapper").css("zoom",$("body").height()/(100+$("#tab-labels").height())));$(function(){setupEvents();createZopim();createSocial();setupTutorialHint()});
function setupEvents(){loadSlideShare(slideShareId);$("#fullscreenMask").click(normalScreen);$("#app-container").keyup(function(a){var b=a.keyCode?a.keyCode:a.which;if(32==b)a.preventDefault(),toggleScreen(),$("#qrcode").hide();else if(38==b||37==b)a.preventDefault(),prevPage();else if(40==b||39==b)a.preventDefault(),nextPage()});$("#tabs").tabs();$('input[title!=""]').hint();$("body").hide().fadeIn(800);$(".social").hide().fadeIn(2E3);$("body").on("click",".sample",function(){$("#dialog").dialog("close");
var a=$(this).text();$("#cnp").val(a);processURL(a,!0)});$("body").on("click",".appLink",function(){var a=$(this).attr("href");window.open(a,"_blank");window.focus()});$("body").on("click",".installLink",function(){var a=$(this).attr("href");0<=window.location.host.indexOf("demobo.com")&&window.chrome&&window.chrome.webstore?chrome.webstore.install(a):(window.open(a,"_blank"),window.focus())});$("body").bind("dragover",function(a){a.preventDefault();$("body").css({background:"#c7F5c5"});return!1});
$("body").bind("dragleave",function(a){a.preventDefault();$("body").css({background:""});return!1});$("body").bind("drop",function(a){a.preventDefault();a.stopPropagation&&a.stopPropagation();$("body").css({background:""});var b=a.originalEvent.dataTransfer.getData("Text");b?processURL(b,!0):handleDropFiles(a.dataTransfer.files);clickTab(2);return!1});$("#cnp").live("input paste",function(a){"cnp"==a.target.id&&"input"==a.type&&processURL($("#cnp").val(),!0)})}
var appData={},flashMovie,curPage=1,scribd_doc,googleDocId="1pM2V_Jy2DIwh-Dldi9DgxfScIFWiAT9yEXVCtyzfWGg",slideShareId="presentationremote-120502003950-phpapp01",curPresentationId,dragElement=null;$.event.props.push("dataTransfer");var z=-40,maxFiles=1,errMessage=0,dataArray=[];
function loadDoc(a){var b=a.split("~");a=b[0];b=b[1];-1==b.indexOf("/")?"googleDocs"==a?loadGoogleDocs(b):"slideShare"==a?loadSlideShare(b):"scribd"==a?loadScribd(b):("pdf"==a||"ppt"==a||"doc"==a)&&loadGviewByURL(b):processURL(b)}function hideAll(){$(".docFrame").hide()}function feedbackClicked(){localStorage.setItem("demobo_feedback_prompt",1);closeAllPrompt()}
function closeAllPrompt(){$("#arrow").remove();$("#pageCover").remove();$("#red-dotted-frame").remove();$("#feedback_tab").parent().css({"z-index":""})}function clickTab(a){$(".selected").removeClass("selected");$("#tab-label"+a).addClass("selected");$('#mid-container div[id^="tabs-"]').hide();$("#tabs-"+a).slideDown("3000");$("#pageCover").trigger("click");2==a&&0==demobo.getPlayers().length&&showQR()}
function loadGoogleDocs(a){curPresentationId=a;googledocURL="https://docs.google.com/presentation/embed?id=";googledocURL+=a;googledocURL+="&start=false&loop=true&delayms=60000";curPage=1;document.getElementById("googledoc").setAttribute("src",googledocURL);hideAll();$("#googledoc").show()}
function loadSlideShare(a){curPresentationId=a;$("#slideshare").replaceWith('<div id="player"></div>');swfobject.embedSWF("http://static.slidesharecdn.com/swf/ssplayer2.swf","player","820","649","8",null,{doc:a,startSlide:1,rel:0},{allowScriptAccess:"always",wmode:"transparent"},{id:"slideshare","class":"docFrame"});flashMovie=document.getElementById("slideshare");hideAll();$("#slideshare").show()}
function loadScribd(a){curPresentationId=a;a=a.split("|")[1];scribd_doc=scribd.Document.getDoc(a);scribd_doc.addParam("height","100%");scribd_doc.addParam("width","100%");scribd_doc.addParam("wmode","transparent");scribd_doc.addParam("mode","list");scribd_doc.addParam("jsapi_version",2);scribd_doc.addEventListener("docReady",function(a){scribd_doc.api.setPage(0)});scribd_doc.write("scribd");hideAll();$("#scribd").show()}
function loadGviewByURL(a){curPresentationId=a;pdfURL="http://docs.google.com/gview?url="+encodeURIComponent(a)+"&a=bi";curPage=1;loadGviewImg(1);hideAll();$("#pdfviewer").show();$("#pdfviewer").scrollTop(0)}function loadGviewImg(a){1==a&&$("#pdfviewer").html("");var b=$('<img src="'+pdfURL+"&pagenumber="+a+'">');$("#pdfviewer").append(b);b.height($("#pdfviewer").height());b.load(function(b){loadGviewImg(a+1)});b.error(function(a){$(this).remove()})}
function toggleScreen(){var a=$(".docFrame:visible");a.toggleClass("fullscreen");$("#fullscreenMask").hide();"pdfviewer"==a.attr("id")&&($("#pdfviewer").scrollTop($("#pdfviewer").scrollTop()*$("#pdfviewer").height()/$("#pdfviewer img").height()),$("#pdfviewer img").height($("#pdfviewer").height()));a.hasClass("fullscreen")&&$("#fullscreenMask").show();closeAllPrompt()}
function normalScreen(){$("#fullscreenMask").hide();var a=$(".docFrame:visible");a.removeClass("fullscreen");"pdfviewer"==a.attr("id")&&($("#pdfviewer").scrollTop($("#pdfviewer").scrollTop()*$("#pdfviewer").height()/$("#pdfviewer img").height()),$("#pdfviewer img").height($("#pdfviewer").height()))}
function nextPage(){$("#slideshare").is(":visible")?document.getElementById("slideshare").next():$("#scribd").is(":visible")?scribd_doc.api.setPage(parseInt(scribd_doc.api.getPage())+1):$("#googledoc").is(":visible")?(curPage++,document.getElementById("googledoc").setAttribute("src",googledocURL+"#"+curPage)):$("#pdfviewer").is(":visible")&&(curPage++,$("#pdfviewer").animate({scrollTop:"+="+$("#pdfviewer").height()},"slow"))}
function prevPage(){$("#slideshare").is(":visible")?document.getElementById("slideshare").previous():$("#scribd").is(":visible")?scribd_doc.api.setPage(parseInt(scribd_doc.api.getPage())-1):$("#googledoc").is(":visible")?(curPage--,0>=curPage?curPage=1:document.getElementById("googledoc").setAttribute("src",googledocURL+"#"+curPage)):$("#pdfviewer").is(":visible")&&(curPage--,0>=curPage?curPage=1:$("#pdfviewer").animate({scrollTop:"-="+$("#pdfviewer").height()},"slow"))}
function addUser(a){demobo.addPlayer(a.deviceID);loadAppData();clickTab(2);$("#qrimage").effect("bounce",{},100);$("#dialog").hasClass("ui-dialog-content")&&$("#dialog").dialog("close")}function saveAppData(a){a&&(appData=a);demobo.setData(demobo.getPlayers()[0],appData)}function loadAppData(){renderRecent();demobo.getData(demobo.getPlayers()[0],"setAppData")}function setAppData(a){appData=a;renderRecent()}
function saveDoc(a,b){if(0!=demobo.getPlayers().length){var c=a+"~"+b;appData.docs||(appData.docs=[]);-1==appData.docs.indexOf(c)&&(appData.docs.push(c),saveAppData(),renderRecent())}}
function renderRecent(){$(".popoverHint").popover("hide");$("#recentDocs").show();$("#panelTitle").text("Recent Files");$("#recentDocs").html("");for(var a in appData.docs){var b=appData.docs[a].split("~"),c=b[0],b=b[1].split("/").reverse(),b="googleDocs"==c?b[1]:b[0],c=$('<div class="item"><div class="link doc" title="'+b+'"><div class="icon '+c+'"></div>'+b+'</div><div class="link remove">x</div></div>');$("#recentDocs").append(c)}a=appData.docs?appData.docs.length:0;$("#tab-label2 .label").text(a);
2==a&&showPopoverLove(a);$("#recentDocs div.doc").click(function(){var a=$("#recentDocs div.doc").index(this);loadDoc(appData.docs[a])});$("#recentDocs div.remove").click(function(){var a=$("#recentDocs div.remove").index(this);appData.docs.splice(a,1);saveAppData(appData);renderRecent()})}
function processURL(a,b){if(-1!=a.indexOf("https://docs.google.com")&&-1!=a.indexOf("/presentation/")){var c=/\?id=/.test(a)?a.split("&")[0].split("?id=")[1]:a.split("/").reverse()[1];c&&(loadGoogleDocs(c),b&&saveDoc("googleDocs",a))}else if(-1!=a.indexOf("http://www.slideshare.net"))$.getJSON("http://www.slideshare.net/api/oembed/2?url="+a+"&format=jsonp&callback=?",function(c){c=c.thumbnail.split("/").reverse()[0].split("-");c.pop();if(c=c.join("-"))loadSlideShare(c),b&&saveDoc("slideShare",a)});
else if(-1!=a.indexOf("http://www.scribd.com"))(c=a.split("/").reverse()[0]+"|"+a.split("/").reverse()[1])?(loadScribd(c),b&&saveDoc("scribd",a)):showMessage("Scribd.com presentation is coming soon.","Message");else if(-1!=a.indexOf(".pdf")){c="pdf";if(-1!=a.indexOf(".dropbox.com/")){if(-1!=a.indexOf("dl-web.dropbox.com/")){showInfoDropbox();return}a=a.replace("www.dropbox.com","dl.dropbox.com");c="dropbox"}b&&saveDoc(c,a);loadGviewByURL(a)}else if(-1!=a.indexOf(".ppt")&&-1==a.indexOf(".pptx")){c=
"ppt";if(-1!=a.indexOf(".dropbox.com/")){if(-1!=a.indexOf("dl-web.dropbox.com/")){showInfoDropbox();return}a=a.replace("www.dropbox.com","dl.dropbox.com");c="dropbox"}b&&saveDoc(c,a);loadGviewByURL(a)}else if(-1!=a.indexOf(".doc")){c="doc";if(-1!=a.indexOf(".dropbox.com/")){if(-1!=a.indexOf("dl-web.dropbox.com/")){showInfoDropbox();return}a=a.replace("www.dropbox.com","dl.dropbox.com");c="dropbox"}b&&saveDoc(c,a);loadGviewByURL(a)}else 0==a.indexOf("http")&&showMessage('We only support slideshare.net, google presentation docs, scribd.com, pdf, ppt and doc files at this moment.<br><br><div class="appLink" href="http://www.slideshare.net/upload" target="_blank">Here</div> is how to upload pdf and ppt to slideshare.net.<br><br><div class="appLink" href="https://support.google.com/drive/bin/answer.py?hl=en&answer=186466" target="_blank">Here</div> is how to convert pdf and ppt into Google Presentation.<br><br><div class="appLink" href="http://support.google.com/drive/bin/answer.py?hl=en&answer=176692" target="_blank">Here</div> is the limitation of Google Drive on PDF conversion into Presentation: the maximum size for pdf file is 2MB.',
"Document url not supported.")}
function showMessage(a,b,c){$(".popoverHint").popover("hide");$("#dialogBody").html(a);a=$("#mid-container").offset().left+9;$("#dialog").dialog({dialogClass:"dialog_style1",title:b,position:[a,0],width:$("body").width()-a,height:$("body").height(),modal:!0,draggable:!1,hide:{effect:"slide",duration:1E3,direction:"right"},show:{effect:"drop",duration:1E3,direction:"right"}});c?$("#qrcode").show():$("#qrcode").hide();$("#disqus_thread").hide();$(".ui-dialog-titlebar-close.ui-corner-all").attr("href",null)}
function showInfoPDF(){showMessage('Drag & drop the file into this app<br><br>Beta Version only supports files less than 500KB.<br>Please upload big files to <div class="appLink" href="http://www.slideshare.net/upload" target="_blank">slideshare.net</div> or <div class="appLink" href="https://drive.google.com" target="_blank">drive.google.com</div>',"Supported files: PDF, PPT and DOC")}
function showInfoDropbox(){showMessage('Copy & paste your Dropbox Share Link url into the text field<br><br>Sample url:<br><div class="sample">https://www.dropbox.com/s/dknkhi1o0y52qke/PresentationDocsTutorial.pdf</div>',"Supported files on Dropbox: PDF, PPT and DOC")}
function showInfoSlideshare(){showMessage('Copy & paste your Slideshare presentation url into the text field<br><br>Sample url:<br><div class="sample">http://www.slideshare.net/cvgallo/7-innovation-secrets-of-steve-jobs</div>',"slideshare.net support")}
function showInfoGoogle(){showMessage('Copy & paste your Google Drive Presentation shared link url into the text field<br><br>Please make sure to share doc as "Public on the web" or "Anyone with the link"<br><br>Sample url:<br><div class="sample">https://docs.google.com/presentation/d/1k8ncT30k5X8fGlo8GEwhIrQZ_1bHseMoERE6IZx2sTo/edit</div><br><br>For animation support, please install the Presenstation Remote for Google Drive extension. Click Speaker Notes on the left for more details.',"Google Drive Presentation support")}
function showInfoScribd(){showMessage('Copy & paste your Scribd shared link url into the text field<br><br>Please make sure to share doc as Public<br><br>Sample url:<br><div class="sample">http://www.scribd.com/doc/100854871/Star-Wars-Origami-Boba-Fett-folding-instructions</div>',"scribd.com support")}
function showQR(){1==demobo.getState()?showMessage('If this is the first time you pair your phone with this browser, click "Create Connection" and scan the following QR code with the phone app. <br><br>Otherwise just click the browser icon on the phone app to connect.',"Connect With Phone",!0):showMessage("Unable to connect to the server. If you have a firewall, it may be blocking the connection on port 8000. Reload the website to retry.","Failed to connect",!1)}
function showFeedback(){$("#dialogBody").html("");var a=$("#mid-container").offset().left;$("#dialog").dialog({dialogClass:"dialog_style1",title:"Feedback",position:[a,0],width:$("body").width()-a,height:$("body").height(),modal:!0,draggable:!1,hide:"fadeOut"});$("#qrcode").hide();$("#disqus_thread").show()}
function showSpeakerNotes(){showMessage('We support speaker notes on slideshare and Google Drive presentation<br><br>Install <div class="installLink" href="https://chrome.google.com/webstore/detail/oichkmlpbknppmikofjkafoifgpnilph">Presentation Remote for Slideshare</div> and then start your presentation on www.slideshare.net.<br><div class="appLink" target="_blank" href="http://www.slideshare.net/cvgallo/7-innovation-secrets-of-steve-jobs">Here</div> is an example with speaker notes.<br><div class="appLink" target="_blank" href="http://help.slideshare.com/entries/20467183-how-do-speaker-notes-get-generated-in-uploaded-presentations-does-this-work-with-all-types-of-files">Here</div> is how to upload speaker notes on slideshare.net.<br><br>Install <div class="installLink" href="https://chrome.google.com/webstore/detail/fjdgmdaaacgdbfdohoidfjiipmbnbnho">Presentation Remote for Google Drive</div> and then start your presentation on docs.google.com.<br><div class="appLink" target="_blank" href="https://docs.google.com/a/demobo.com/presentation/d/1k8ncT30k5X8fGlo8GEwhIrQZ_1bHseMoERE6IZx2sTo/edit#slide=id.p">Here</div> is an example with speaker notes.<br><div class="appLink" target="_blank" href="http://support.google.com/drive/bin/answer.py?hl=en&answer=1696743">Here</div> is how to upload speaker notes on Google Presentation.',"Speaker Notes",
!1)}
function handleDropFiles(a){$.each(a,function(b,c){if(!(0<b)){if(!a[b].type.match("application/pdf")&&!a[b].type.match("application/vnd.openxmlformats-officedocument.presentationml.presentation")&&!a[b].type.match("application/vnd.ms-powerpoint")&&!a[b].type.match("application/msword")&&!a[b].type.match("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"))return showMessage("We only support PDF, PPT, XLS and DOC files","Document format not supported."),!1;var d=new FileReader;d.onload=
function(a){return function(b){dataArray=[{name:a.name,value:this.result,guid:DEMOBO.roomID}];localStorage.getItem(a.name)==a.size?processURL("http://net.demobo.com/dnd/docs/"+DEMOBO.roomID+"/"+a.name):uploadFile(a)}}(a[b]);d.readAsDataURL(c)}})}function restartFiles(){dataArray.length=0;return!1}
function uploadFile(a){var b=100/dataArray.length,c=0;$.each(dataArray,function(d,e){5E5<a.size?showMessage('Beta Version only supports files less than 500KB. Please upload files to <div class="appLink" href="http://www.slideshare.net/upload" target="_blank">slideshare.net</div> or <div class="appLink" href="https://drive.google.com" target="_blank">drive.google.com</div><br><br><div class="appLink" href="http://www.slideshare.net/upload" target="_blank">Here</div> is how to upload pdf and ppt to slideshare.net.<br><br><div class="appLink" href="https://support.google.com/drive/bin/answer.py?hl=en&answer=186466" target="_blank">Here</div> is how to convert pdf and ppt into Google Presentation.<br><br><div class="appLink" href="http://support.google.com/drive/bin/answer.py?hl=en&answer=176692" target="_blank">Here</div> is the limitation of Google Drive on PDF conversion into Presentation: the maximum size for pdf file is 2MB.',"Document too large."):
$.post("http://net.demobo.com/dnd/upload.php",dataArray[d],function(d){++c;100==b*c&&setTimeout(restartFiles,500);d=d.split(":");"uploaded successfully"==d[1]?(processURL("http://net.demobo.com/dnd/docs/"+d[0],!0),localStorage.setItem(a.name,a.size)):showMessage("Upload failed","")})});return!1}
function setupTutorialHint(){$("#checked.popoverHint").popover({html:!0,title:'Hint:<button type="button" class="close">&times;</button>',content:"Enable this for phone flicking.",trigger:"manual",placement:"right"});$("#download.popoverHint").popover({html:!0,title:'Hint:<button type="button" class="close">&times;</button>',content:"You need the de Mobo phone app for this to work.",trigger:"manual",placement:"right"});$("#cnpdiv.popoverHint").popover({html:!0,title:'Hint:<button type="button" class="close">&times;</button>',
content:"Put your presentation link here. Drag and drop also works.",trigger:"manual",placement:"top"});$(".connect.popoverHint").popover({html:!0,title:'Hint:<button type="button" class="close">&times;</button>',content:"Click this to show QR code for connecting with phone.",trigger:"manual",placement:"right"});$(".popoverLove").popover({html:!0,title:'<button type="button" class="close">&times;</button>',content:"Give us some love.",trigger:"manual",placement:"top"});$("body").on("click",".popover-title .close",
function(){$(this).parents(".popover").hide()});$("body").on("mousedown","#slideshare",function(){curPresentationId==slideShareId&&setTimeout(function(){switch(document.getElementById("slideshare").getCurrentSlide()){case 3:$("#download.popoverHint").popover("show");break;case 4:$(".connect.popoverHint").popover("show");break;case 5:$("#cnpdiv.popoverHint").popover("show");break;case 6:$("#checked.popoverHint").popover("show")}},200)});$(".help").click(function(){$(".popoverHint").data("popover").tip().hasClass("in")?
$(".popoverHint").popover("hide"):$(".popoverHint").popover("show")})}function showPopoverLove(a){var b=["googleplus","cws"];a-=1;1!=localStorage.getItem(b[a])&&b[a]&&($(".popoverLove").popover("show"),$(".popoverLove").next().addClass("love").find(".popover-title .close").one("click",function(){localStorage.setItem(b[a],1)}))}
function createZopim(){window.$zopim||function(a,b){var c=$zopim=function(a){c._.push(a)},d=c.s=a.createElement(b),e=a.getElementsByTagName(b)[0];c.set=function(a){c.set._.push(a)};c._=[];c.set._=[];d.async=!0;d.setAttribute("charset","utf-8");d.src="//cdn.zopim.com/?yUlZMlln6qDfObYzYoZiApbspV3KB8vW";c.t=+new Date;d.type="text/javascript";e.parentNode.insertBefore(d,e)}(document,"script");$zopim(function(){$zopim.livechat.bubble.setTitle("Need help?");$zopim.livechat.bubble.setText("Click here for livechat!");
$(".zopim").hide().fadeIn(2E3,function(){$zopim.livechat.bubble.hide();$zopim.livechat.window.hide()})});document.body.onclick=function(){$zopim&&$zopim.livechat&&$zopim.livechat.window.hide()}}
function createSocial(){(function(a,b,c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//connect.facebook.net/en_US/all.js#xfbml=1&appId=229610010412672",d.parentNode.insertBefore(a,d))})(document,"script","facebook-jssdk");(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src="https://apis.google.com/js/plusone.js";var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)})();!function(a,b,
c){var d=a.getElementsByTagName(b)[0];a.getElementById(c)||(a=a.createElement(b),a.id=c,a.src="//platform.twitter.com/widgets.js",d.parentNode.insertBefore(a,d))}(document,"script","twitter-wjs");setTimeout(function(){window.FB||$(".fb-like").hide();window.gapi||$(".g-plusone").hide();window.twttr||$(".twitter-share-button").hide()},3E3)}
(function(a){a.fn.hint=function(b){b||(b="blur");return this.each(function(){function c(){d.val()===e&&d.hasClass(b)&&d.val("").removeClass(b)}var d=a(this),e=d.attr("title"),f=a(this.form),g=a(window);e&&(d.blur(function(){""===this.value&&d.val(e).addClass(b)}).focus(c).blur(),f.submit(c),g.unload(c))})}})(jQuery);
